apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-auth
  labels:
    app: fc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-auth
  template:
    metadata:
      labels:
        app: fc-auth
    spec:
      containers:
        - name: fc-auth
          image: sthanguy/fc-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: firebase-secret
              mountPath: "/usr/route/config/firebase"
              readOnly: true
            - name: session-secret
              mountPath: "usr/route/config/session"
              readOnly: true
            - name: gh
              mountPath: "usr/route/config/gh"
              readOnly: true
        - name: fc-logging
          image: sthanguy/fc-logging:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: custom-webhook-secret
              mountPath: "/usr/logger/config/custom/"
              readOnly: true
      volumes:
        - name: firebase-secret
          secret:
            secretName: firebase-secret
        - name: session-secret
          secret:
            secretName: session-secret
        - name: gh
          secret:
            secretName: github-auth-secret
            items:
            - key: id
              path: id
            - key: secret
              path: secret
        - name: custom-webhook-secret
          secret:
            secretName: custom-webhook-secret
            items:
            - key: secret
              path: secret