apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkite
  labels:
    app: buildkite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkite
  template:
    metadata:
      labels:
        app: buildkite
    spec:
      containers:
        - name: buildkite
          image: buildkite/agent:3
          imagePullPolicy: Always
          volumeMounts:
            - name: var-run-docker-sock
              mountPath: /var/run/docker.sock
          env:
            - name: BUILDKITE_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildkite
                  key: secret
                  optional: false
      volumes:
        - name: var-run-docker-sock
          hostPath:
            path: /var/run/docker.sock
 
