apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-session-cache
  labels:
    app: fc-session-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-session-cache
  template:
    metadata:
      labels:
        app: fc-session-cache
    spec:
      containers:
        - name: fc-session-cache
          image: sthanguy/fc-session-cache:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          env:
          - name: FC_SESSION_CACHE_USERNAME
            valueFrom:
              secretKeyRef:
                name: session-cache-secret
                key: username
                optional: false
          - name: FC_SESSION_CACHE_PASSWORD
            valueFrom:
            secretKeyRef:
              name: session-cache-secret
              key: password
              optional: false
