apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-provision
  labels:
    app: fc-provision
  annotations:
    container.apparmor.security.beta.kubernetes.io/img: unconfined
    container.seccomp.security.alpha.kubernetes.io/img: unconfined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-provision
  template:
    metadata:
      labels:
        app: fc-provision
    spec:
      containers:
        - name: fc-provision
          image: sthanguy/fc-provision:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: registry-certs
              mountPath: /certs
              readOnly: true
          env:
          - name: FC_BUILDER_USERNAME
            valueFrom:
              secretKeyRef:
                name: builder-secret
                key: username
                optional: false
          - name: FC_BUILDER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: builder-secret
                key: password
                optional: false
          - name: FC_SESSION_CACHE_USERNAME
            valueFrom:
              secretKeyRef:
                name: session-cache-secret
                key: username
                optional: false
          - name: FC_SESSION_CACHE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: session-cache-secret
                key: password
                optional: false
      volumes:
        - name: registry-certs
          secret:
            secretName: registry-cert
