apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-registry
  labels:
    app: fc-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-registry
  template:
    metadata:
      labels:
        app: fc-registry
    spec:
      containers:
        - name: fc-registry
          image: registry:2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/tls.key
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: fc-registry
              mountPath: /var/lib/fc-registry
              subPath: fc-registry
      volumes:
        - name: certs
          secret:
            secretName: docker-registry-tls-cert
        - name: fc-registry
          persistentVolumeClaim:
            claimName: registry-pvc
