apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-registry
  labels:
    app: fc-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-registry
  template:
    metadata:
      labels:
        app: fc-registry
    spec:
      containers:
        - name: fc-registry
          image: registry:2
          ports:
            - containerPort: 5000
          #env:
          # - name: REGISTRY_HTTP_TLS_CERTIFICATE
          #   value: /etc/registry/tls/tls.crt
          # - name: REGISTRY_HTTP_TLS_KEY
          #   value: /etc/registry/tls/tls.key
          volumeMounts:
            - name: registry-certs
              mountPath: /etc/registry/tls
              readOnly: true
            - name: fc-registry
              mountPath: /var/lib/fc-registry
              subPath: fc-registry
      volumes:
        - name: registry-certs
          secret:
            secretName: registry-cert
        - name: fc-registry
          persistentVolumeClaim:
            claimName: registry-pvc
