apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-upload
  labels:
    app: fc-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fc-upload
  template:
    metadata:
      labels:
        app: fc-upload
    spec:
      containers:
        - name: fc-upload
          image: sthanguy/fc-upload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: session-secret
              mountPath: "/usr/route/config/session"
          env:
          - name: FC_BUILDER_USERNAME
            valueFrom:
              secretKeyRef:
                name: builder-secret
                key: username 
                optional: false
          - name: FC_BUILDER_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: builder-secret
                key: password
                optional: false
          - name: FC_SESSION_CACHE_USERNAME
            valueFrom:
              secretKeyRef:
                name: session-cache-secret
                key: username
                optional: false
          - name: FC_SESSION_CACHE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: session-cache-secret
                key: password
                optional: false
        - name: fc-logging
          image: sthanguy/fc-logging:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: custom-webhook-secret
              mountPath: "/usr/logger/config/custom/"
              readOnly: true
      volumes:
        - name: custom-webhook-secret
          secret:
            secretName: custom-webhook-secret
            items:
            - key: secret
              path: secret
        - name: session-secret
          secret:
            secretName: session-secret
            items:
            - key: secret
              path: secret
