name: Microservice Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Auth microservice
        run: docker build ./services/auth --tag "sthanguy/fc-auth:$GITHUB_SHA"

      - name: Build the Subscribe microservice
        run: docker build ./services/subscribe --tag "sthanguy/fc-subscribe:$GITHUB_SHA"

      - name: Build the Deploy microservice
        run: docker build ./services/deploy --tag "sthanguy/fc-deploy:$GITHUB_SHA"

      - name: Build the Gateway microservice
        run: docker build ./services/gateway --tag "sthanguy/fc-gateway:$GITHUB_SHA"

      - name: Build the Upload microservice
        run: docker build ./services/gateway --tag "sthanguy/fc-upload:$GITHUB_SHA"

      - name: Build the Logging sidecar
        run: docker build ./services/logging --tag "sthanguy/fc-logging:$GITHUB_SHA"

      - name: Login to Docker Registry
        run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
